### ISSUE TITLE
Want annotations for Twitter dataset

### ISSUE THREAD

**Issue by SuYindu** [kite1988/velda#1]
Dear Dr. Chen:

I am Su Yindu, a graduate student of Computer Science and Technology at Zhejiang University of China.
My research is focused on multi-modal learning and I am working on a task about image-text relation.

Recently I have read your paper _VELDA: Relating an Image Tweet's Text and Images_. It is very interesting and enlightening.
For further research, I would like to ask whether it is possible for you to share with me the annotation of Twitter dataset?
I can't find them in this repository.
This would be a great help for my further research.

Please be assured that everything you share with me will be used only for my research purposes and will not be shared with any third-party.

I appreciate your kind consideration and look forward to your reply.

**Comment by kite1988** [comment]
Hi Yindu,

We have released the twitter post ids at: https://github.com/kite1988/velda/tree/master/dataset/Twitter. Due to the Twitter policy, we were unable to release the actual post content.  You can use Twitter lookup [API](https://developer.twitter.com/en/docs/twitter-api/tweets/lookup/api-reference/get-tweets-id) to obtain the tweet information.

Hope that helps.
Tao

**Comment by SuYindu** [comment]
Dr.Chen, thank you for your time.

I am a bit confused: I do find the Twitter IDs but there is no corresponding labels or separate file for each category. Do I miss something?

**Comment by kite1988** [comment]
In this paper, we do not have explicit labels (ie, "emotion" or "visual") for image-text relationship and our VELDA model tries to learn such relationship automatically.

In our prior work, we have human labeled image-text relationship ("visual" and "non-visual")  for Weibo dataset only: https://github.com/kite1988/visual-image-tweets

**Comment by SuYindu** [comment]
Now I got it. The human-labeled Weibo dataset is exactly what I need.

Thank you for your patience and help!
